/**
 * Firewall simulation engine.
 * Simulates packet traversal through UniFi firewall rules including implicit
 * rules generated by UniFi automatically (conntrack, DHCP, guest isolation, etc.)
 */

// ── Types ─────────────────────────────────────────────────────────────────────

export type SimVerdict = 'ALLOW' | 'DROP' | 'REJECT' | 'UNCERTAIN'

export interface SimRule {
  id: string
  name: string
  priority: number        // lower = earlier in evaluation
  enabled: boolean
  action: 'accept' | 'drop' | 'reject'
  protocol?: string       // 'all' | 'tcp' | 'udp' | 'icmp' | undefined = any
  srcAddress?: string     // CIDR, IP, 'any', undefined = any
  dstAddress?: string     // CIDR, IP, 'any', undefined = any
  srcPort?: string        // port spec or undefined = any
  dstPort?: string        // port spec or undefined = any
  conntrackStates?: string[]  // for implicit established/related/invalid
  isImplicit: boolean
  ruleset?: string
  implicitSource?: string // human-readable reason for implicit rule
}

export interface TraceEntry {
  ruleId: string
  ruleName: string
  isImplicit: boolean
  implicitSource?: string
  action: 'match' | 'skip' | 'skip-disabled'
  skipReason?: string     // why rule was skipped
}

export interface SimulationResult {
  verdict: SimVerdict
  matchedRule: SimRule | null
  trace: TraceEntry[]
  defaultAction: 'DROP'
  caveats: string[]
}

export interface SimulateParams {
  srcIp: string
  dstIp: string
  dstPort?: number
  proto?: 'tcp' | 'udp' | 'icmp' | 'all'
  hypotheticalRules?: Array<{
    id: string
    enabled?: boolean
    action?: string
    srcAddress?: string
    dstAddress?: string
    dstPort?: string
    protocol?: string
  }>
}

/** Normalized firewall rule from API */
export interface ApiFirewallRule {
  id: string
  name: string
  enabled: boolean
  action: string
  protocol: string
  srcAddress: string
  dstAddress: string
  srcPort: string
  dstPort: string
  ruleset: string
}

/** Normalized network from API */
export interface ApiNetwork {
  id: string
  name: string
  purpose: string
  vlan?: number
  cidr: string
  gateway: string
  enabled: boolean
}

// ── IP / CIDR helpers ─────────────────────────────────────────────────────────

/** Convert a dotted-decimal IP string to a 32-bit unsigned integer */
function ipToInt(ip: string): number {
  const parts = ip.trim().split('.')
  if (parts.length !== 4) return 0
  return (
    ((parseInt(parts[0], 10) & 0xff) << 24) |
    ((parseInt(parts[1], 10) & 0xff) << 16) |
    ((parseInt(parts[2], 10) & 0xff) << 8)  |
    (parseInt(parts[3], 10) & 0xff)
  ) >>> 0
}

/**
 * Returns true if `ip` falls within `cidr`.
 *
 * Special cases:
 * - 'any' or '' → true
 * - '0.0.0.0/0' → true
 * - No slash → exact IP match
 * - Starts with '!' → negate result (UniFi negated addresses)
 * - Contains non-IP characters (address group name) → returns a sentinel
 *   object; callers must handle this via `matchResult`
 */
function ipInCidr(ip: string, cidr: string): boolean | 'UNCERTAIN' {
  if (!cidr || cidr === 'any' || cidr === '0.0.0.0/0') return true

  // Handle negation prefix (UniFi address groups / negated addresses)
  const negated = cidr.startsWith('!')
  const spec = negated ? cidr.slice(1).trim() : cidr

  // If the spec contains non-IP/CIDR characters it's an address group name
  // that we cannot resolve at simulation time
  if (/[^0-9./]/.test(spec)) return 'UNCERTAIN'

  let result: boolean
  if (spec.includes('/')) {
    const [baseStr, prefixStr] = spec.split('/')
    const prefix = parseInt(prefixStr, 10)
    if (isNaN(prefix) || prefix < 0 || prefix > 32) return false
    const mask = prefix === 0 ? 0 : (~0 << (32 - prefix)) >>> 0
    result = (ipToInt(ip) & mask) === (ipToInt(baseStr) & mask)
  } else {
    result = ip.trim() === spec.trim()
  }

  return negated ? !result : result
}

/**
 * Returns true if `port` matches `portSpec`.
 *
 * Supported formats:
 * - undefined / '' / 'any' → always matches
 * - '80' → exact match
 * - '80-443' → range
 * - '80,443,8080' → comma-separated list
 * - '80-100,443,8080-8090' → combined
 */
function portMatches(port: number | undefined, portSpec: string | undefined): boolean {
  if (port === undefined) return true
  if (!portSpec || portSpec === 'any' || portSpec === '') return true

  const parts = portSpec.split(',')
  for (const part of parts) {
    const trimmed = part.trim()
    if (trimmed.includes('-')) {
      const [lo, hi] = trimmed.split('-').map(s => parseInt(s, 10))
      if (!isNaN(lo) && !isNaN(hi) && port >= lo && port <= hi) return true
    } else {
      const n = parseInt(trimmed, 10)
      if (!isNaN(n) && port === n) return true
    }
  }
  return false
}

/**
 * Returns true if the requested protocol matches the rule protocol.
 * 'all', undefined, or '' means match anything.
 */
function protoMatches(requestProto: string | undefined, ruleProto: string | undefined): boolean {
  if (!ruleProto || ruleProto === 'all' || ruleProto === '') return true
  if (!requestProto || requestProto === 'all' || requestProto === '') return true
  return requestProto.toLowerCase() === ruleProto.toLowerCase()
}

/**
 * Determine whether conntrack states match the simulated packet context.
 * We always simulate NEW (outbound) connections.
 *
 * - ESTABLISHED / RELATED → only match non-new (existing) connections → false for new
 * - INVALID → only match broken/invalid packets → false for normal new connections
 * - NEW → matches new connections → true
 */
function conntrackMatch(states: string[] | undefined, requestIsNew: boolean): boolean {
  if (!states || states.length === 0) return true

  // If any state is ESTABLISHED or RELATED — this rule is for existing connections
  if (states.some(s => s === 'ESTABLISHED' || s === 'RELATED')) {
    return !requestIsNew
  }
  // INVALID packets — never a normal new connection
  if (states.includes('INVALID')) {
    return false
  }
  // NEW state → matches new connections
  if (states.includes('NEW')) {
    return requestIsNew
  }
  return true
}

// ── Static implicit rules ─────────────────────────────────────────────────────

const STATIC_IMPLICIT_RULES: SimRule[] = [
  {
    id: '__implicit_established',
    name: '[Auto] Allow Established / Related',
    priority: -300,
    enabled: true,
    action: 'accept',
    conntrackStates: ['ESTABLISHED', 'RELATED'],
    isImplicit: true,
    implicitSource: 'iptables conntrack — alle UniFi Versionen',
  },
  {
    id: '__implicit_invalid',
    name: '[Auto] Drop Invalid State',
    priority: -200,
    enabled: true,
    action: 'drop',
    conntrackStates: ['INVALID'],
    isImplicit: true,
    implicitSource: 'iptables conntrack invalid state',
  },
  {
    id: '__implicit_dhcp',
    name: '[Auto] Allow DHCP',
    priority: -100,
    enabled: true,
    action: 'accept',
    protocol: 'udp',
    dstPort: '67',
    srcPort: '68',
    isImplicit: true,
    implicitSource: 'UniFi DHCP Service',
  },
]

const DEFAULT_DENY_RULE: SimRule = {
  id: '__implicit_default_deny',
  name: '[Auto] Default Deny (Implicit)',
  priority: 99999,
  enabled: true,
  action: 'drop',
  isImplicit: true,
  implicitSource: 'UniFi Implicit Default — kein ACCEPT = DROP',
}

// ── Dynamic implicit rules ────────────────────────────────────────────────────

const RFC1918 = ['10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16']

export function buildImplicitRules(networks: ApiNetwork[]): SimRule[] {
  const rules: SimRule[] = []

  for (const network of networks) {
    if (!network.cidr) continue

    // Intra-subnet: allow traffic within the same subnet
    rules.push({
      id: `__implicit_intra_${network.id}`,
      name: `[Auto] Intra-${network.name} erlaubt`,
      priority: -60,
      enabled: true,
      action: 'accept',
      srcAddress: network.cidr,
      dstAddress: network.cidr,
      isImplicit: true,
      implicitSource: 'Intra-Subnet Routing (nicht gefiltert)',
    })

    // Guest network isolation: block guest → RFC1918 addresses
    if (network.purpose === 'guest') {
      for (const rfc of RFC1918) {
        rules.push({
          id: `__implicit_guest_${network.id}_${rfc.replace(/[./]/g, '_')}`,
          name: `[Auto] Block Guest-VLAN ${network.vlan ?? network.name} → RFC1918`,
          priority: -50,
          enabled: true,
          action: 'drop',
          srcAddress: network.cidr,
          dstAddress: rfc,
          isImplicit: true,
          implicitSource: 'UniFi Guest Network Isolation',
        })
      }
    }
  }

  return rules
}

// ── Conversion: API rules → SimRules ─────────────────────────────────────────

function apiRuleToSimRule(rule: ApiFirewallRule, index: number): SimRule {
  return {
    id: rule.id,
    name: rule.name,
    priority: index * 10,
    enabled: rule.enabled,
    action: rule.action as 'accept' | 'drop' | 'reject',
    protocol: rule.protocol || undefined,
    srcAddress: rule.srcAddress || undefined,
    dstAddress: rule.dstAddress || undefined,
    srcPort: rule.srcPort || undefined,
    dstPort: rule.dstPort || undefined,
    isImplicit: false,
    ruleset: rule.ruleset,
  }
}

// ── Main simulation function ──────────────────────────────────────────────────

export function simulatePacket(
  params: SimulateParams,
  apiRules: ApiFirewallRule[],
  networks: ApiNetwork[],
): SimulationResult {
  const { srcIp, dstIp, dstPort, proto } = params
  const requestIsNew = true // We always simulate new connections

  // 1. Build all rule sets
  const staticRules = [...STATIC_IMPLICIT_RULES]
  const dynamicRules = buildImplicitRules(networks)

  // 2. Convert API rules → SimRules
  let userRules: SimRule[] = apiRules.map((r, i) => apiRuleToSimRule(r, i))

  // 3. Apply hypothetical patches
  if (params.hypotheticalRules && params.hypotheticalRules.length > 0) {
    for (const patch of params.hypotheticalRules) {
      const idx = userRules.findIndex(r => r.id === patch.id)
      if (idx !== -1) {
        userRules[idx] = {
          ...userRules[idx],
          ...(patch.enabled    !== undefined && { enabled: patch.enabled }),
          ...(patch.action     !== undefined && { action: patch.action as 'accept' | 'drop' | 'reject' }),
          ...(patch.srcAddress !== undefined && { srcAddress: patch.srcAddress }),
          ...(patch.dstAddress !== undefined && { dstAddress: patch.dstAddress }),
          ...(patch.dstPort    !== undefined && { dstPort: patch.dstPort }),
          ...(patch.protocol   !== undefined && { protocol: patch.protocol }),
        }
      }
    }
  }

  // 4. Merge and sort all rules by priority
  const allRules: SimRule[] = [
    ...staticRules,
    ...dynamicRules,
    ...userRules,
    DEFAULT_DENY_RULE,
  ].sort((a, b) => a.priority - b.priority)

  // 5. Walk through rules
  const trace: TraceEntry[] = []
  const caveats: Set<string> = new Set([
    'Neue Verbindungen simuliert (kein etablierter conntrack-Status)',
    'NAT/Masquerade und Interface-Binding nicht berücksichtigt',
  ])

  let verdict: SimVerdict = 'DROP'
  let matchedRule: SimRule | null = null
  let foundMatch = false

  for (const rule of allRules) {
    if (foundMatch) break

    // Skip disabled rules
    if (!rule.enabled) {
      trace.push({
        ruleId: rule.id,
        ruleName: rule.name,
        isImplicit: rule.isImplicit,
        implicitSource: rule.implicitSource,
        action: 'skip-disabled',
        skipReason: 'Regel deaktiviert',
      })
      continue
    }

    // ── Conntrack state checks ──────────────────────────────────────────────

    if (rule.conntrackStates && rule.conntrackStates.length > 0) {
      if (rule.conntrackStates.some(s => s === 'ESTABLISHED' || s === 'RELATED')) {
        trace.push({
          ruleId: rule.id,
          ruleName: rule.name,
          isImplicit: rule.isImplicit,
          implicitSource: rule.implicitSource,
          action: 'skip',
          skipReason: 'Neue Verbindung (kein established state)',
        })
        continue
      }
      if (rule.conntrackStates.includes('INVALID')) {
        trace.push({
          ruleId: rule.id,
          ruleName: rule.name,
          isImplicit: rule.isImplicit,
          implicitSource: rule.implicitSource,
          action: 'skip',
          skipReason: 'Nur für ungültige Pakete',
        })
        continue
      }
    }

    // ── DHCP special handling ───────────────────────────────────────────────
    // The implicit DHCP rule only matches DHCP traffic (udp/68→67)
    if (rule.id === '__implicit_dhcp') {
      const isDhcp = proto === 'udp' && dstPort === 67
      if (!isDhcp) {
        trace.push({
          ruleId: rule.id,
          ruleName: rule.name,
          isImplicit: rule.isImplicit,
          implicitSource: rule.implicitSource,
          action: 'skip',
          skipReason: 'Kein DHCP-Verkehr (UDP Port 67/68)',
        })
        continue
      }
    }

    // ── Match src / dst / port / proto ──────────────────────────────────────
    let skipReason: string | undefined

    // Source address
    const srcMatch = rule.srcAddress ? ipInCidr(srcIp, rule.srcAddress) : true
    if (srcMatch === 'UNCERTAIN') {
      caveats.add('Adressgruppen konnten nicht aufgelöst werden')
      trace.push({
        ruleId: rule.id,
        ruleName: rule.name,
        isImplicit: rule.isImplicit,
        implicitSource: rule.implicitSource,
        action: 'skip',
        skipReason: `Quelladresse konnte nicht aufgelöst werden (Adressgruppe: ${rule.srcAddress})`,
      })
      continue
    }
    if (!srcMatch) {
      skipReason = `Quelladresse ${srcIp} passt nicht zu ${rule.srcAddress}`
    }

    // Destination address
    if (!skipReason) {
      const dstMatch = rule.dstAddress ? ipInCidr(dstIp, rule.dstAddress) : true
      if (dstMatch === 'UNCERTAIN') {
        caveats.add('Adressgruppen konnten nicht aufgelöst werden')
        trace.push({
          ruleId: rule.id,
          ruleName: rule.name,
          isImplicit: rule.isImplicit,
          implicitSource: rule.implicitSource,
          action: 'skip',
          skipReason: `Zieladresse konnte nicht aufgelöst werden (Adressgruppe: ${rule.dstAddress})`,
        })
        continue
      }
      if (!dstMatch) {
        skipReason = `Zieladresse ${dstIp} passt nicht zu ${rule.dstAddress}`
      }
    }

    // Destination port
    if (!skipReason && !portMatches(dstPort, rule.dstPort)) {
      skipReason = `Zielport ${dstPort ?? '–'} passt nicht zu ${rule.dstPort}`
    }

    // Protocol
    if (!skipReason && !protoMatches(proto, rule.protocol)) {
      skipReason = `Protokoll ${proto ?? 'any'} passt nicht zu ${rule.protocol}`
    }

    if (skipReason) {
      trace.push({
        ruleId: rule.id,
        ruleName: rule.name,
        isImplicit: rule.isImplicit,
        implicitSource: rule.implicitSource,
        action: 'skip',
        skipReason,
      })
      continue
    }

    // ── All conditions matched ──────────────────────────────────────────────
    trace.push({
      ruleId: rule.id,
      ruleName: rule.name,
      isImplicit: rule.isImplicit,
      implicitSource: rule.implicitSource,
      action: 'match',
    })

    matchedRule = rule
    foundMatch = true

    switch (rule.action) {
      case 'accept': verdict = 'ALLOW';  break
      case 'drop':   verdict = 'DROP';   break
      case 'reject': verdict = 'REJECT'; break
      default:       verdict = 'UNCERTAIN'
    }
  }

  return {
    verdict,
    matchedRule,
    trace,
    defaultAction: 'DROP',
    caveats: Array.from(caveats),
  }
}
